repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [ --remove-all-unused-imports,
                --in-place,
                --exclude,
                env.py, ]
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black
        args: # arguments to configure black
          - --line-length=99
          - --target-version=py311
          # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist|
            \.pytest_cache|
            \.dockerignore|
            scripts|alembic|
            venv|
            __pycache__"""

        language_version: python3.11
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: (venv/ | alembic/)
        args: [ "--profile", "black", "--filter-files" ]

  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [ python ]
        require_serial: true
        args: [ "--config=.flake8" ]
        exclude: (venv/|alembic/)

